### ISSUE TITLE
Can't download a specific episode

### ISSUE THREAD

**Issue by Marigem** [vignedev/twist-dl#12]
Haven't had any problems thus far, except for this one:
https://twist.moe/a/the-god-of-high-school/6
The episode is working fine on the website.
I am getting this error:
![1err](https://user-images.githubusercontent.com/43501741/92307514-5dbd2b00-ef97-11ea-8fe3-68def78d0544.png)

I tried the different ways to download like using the CLI and also tried downloading in another folder.

**Comment by vignedev** [comment]
On a closer look it seems to be caused by the server not reporting `Content-Length` correctly. Will investigate further.

For now, you can work around it by using the `--silent` argument, which hides the progress bar.

**Comment by Marigem** [comment]
I used `--silent` and it worked just fine. Thank you!
