### ISSUE TITLE
Outdated x-access-token

### ISSUE THREAD

**Issue by MrSimmmons** [vignedev/twist-dl#15]
old: 1rj2vRtegS8Y60B3w3qNZm5T2Q0TN2NR
new: 0df14814b9e590a1f26d3071a4ed7974

Old one doesnt seem to work anymore. Returns a 401 access denied

**Comment by vignedev** [comment]
Hey there, sorry for the late response.

Thank you for notifying me, I've updated the `accessToken` in both the repository and `npm`.

**Comment by MrSimmmons** [comment]
Awesome works now. Thanks!
