### ISSUE TITLE
Source string encryption has changed on newer shows

### ISSUE THREAD

**Issue by MrSimmmons** [vignedev/twist-dl#16]
Also, It seems that the episode source string encryption has changed for newer shows. Using the current `aesKey` variable returns a `Mailformed UTF-8 data` error when trying to download newer shows.

Source string for an episode uploaded last year:
```
U2FsdGVkX19VIjFyu28cnS0zfwOuRHZsp6v/4AY6jInIMHtkvAmWiLbzzfsgUdOrQ0U/ItuTAEtALBd+8x799AaytZUjjDcg/sAKgBD5+ZY56hfmlisbwoCNj/aXZYxBv5heSRtWbjG+DuHUzVHmMQ==

length = 152
```
Source for a new show uploaded a few days ago:
```
U2FsdGVkX1+tXF3Nk1ZTrSn5Qj7VifQG9e2rPIIF8F23bC8hjfq7IjfZ3sQ7g73ZwKWsuawDOSdWvcajp74ZN/KJn40YpGENlGw87//oUiVHJBHrgkq108qukZ+OAfENpIzmLxrf5gnK/0Kpu2mEFAchR28/29LFNwbxYdHd82VlkZyJGO+7idbIx9jwfgMJ

length = 192
```
So its quite a bit longer

Unsure as to whether or not this encryption change will be changed on all existing sources as well, but might be a good idea to keep in mind that they might.

**Comment by vignedev** [comment]
Hey there,

Thank you for notifying me. I've just updated the both the `accessToken` and `aesKey` in the repository and npm. The encryption has not been changed method has not been changed, just the key itself. The different lengths of the source strings are relative to the length of the decrypted string.

**Comment by MrSimmmons** [comment]
Ahh true that makes a lot of sense. If you don't mind me asking, how did you find the new key? I can find the `accessToken` pretty easily on their site, but I cant seem to find the key.

**Comment by vignedev** [comment]
I don't want to disclose much information about it, but basically a few minutes of digging through the site itself will get you the key that you're looking for.

**Comment by MrSimmmons** [comment]
Makes sense. Thanks for fixing it :)
