### ISSUE TITLE
gui?

### ISSUE THREAD

**Issue by KraXen72** [vignedev/twist-dl#17]
can you guys make a gui? if no, how would i go about making a gui?

thanks.

**Comment by vignedev** [comment]
Hey there,

there are currently no plans for an GUI since the CLI interface is already quite user-friendly enough. Also there aren't any lightweight NodeJS UI libraries that I'm aware of.

**Comment by KraXen72** [comment]
hi, i am making an electron gui using this node package and the functions from it, would you be interested in the result?

**Comment by KraXen72** [comment]
https://github.com/KraXen72/animetwist-dl-electron yeah so this is what i made, you can check it out
