### ISSUE TITLE
"Server responded with 401 (Unauthorized)"

### ISSUE THREAD

**Issue by TimBenninghoff** [vignedev/twist-dl#19]
Worked before, now suddenly getting an error. I guess Twist started acting against external downloaders? Or can I fix this somehow?

![image](https://user-images.githubusercontent.com/62556487/108583232-654f7100-7338-11eb-9e31-310fb8529da7.png)

**Comment by vignedev** [comment]
Hey there,

it seems to be working fine on my side. Are you using the latest version of `twist-dl`?

**Comment by vignedev** [comment]
Closed due to inactivity and inability to replicate said issue.
