### ISSUE TITLE
Episode-Selection

### ISSUE THREAD

**Issue by giusy** [vignedev/twist-dl#2]
If you search for an anime and than want to select an episode greater than 10 it won't work. 
You can only use number 0-9 on the keyboard. Or 'a' 'g' 'i' to select all. That's for me on a mac.

**Comment by vignedev** [comment]
I don't have an Apple device to test this on, but you should be able to choose episodes by using **arrow keys** (*up and down*), selecting them with **Space** and then downloading chosen episodes by pressing **Enter**.

**Comment by giusy** [comment]
silly me. Works perfectly! thx

**Comment by giusy** [comment]
silly me. Works perfectly! thx

**Comment by giusy** [comment]
silly me. Works perfectly! thx
