### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by hennemon** [vignedev/twist-dl#24]
Hi,

when running this command: twist-dl -a "quanzhi-fashi-4th-season" -e 1

I get the following:

>   Quanzhi Fashi 4th Season
error:  Failed to download episode 1
 TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:116:13)
    at request (https.js:289:10)
    at /usr/local/lib/node_modules/twist-dl/node_modules/node-fetch/lib/index.js:1438:15
    at new Promise (<anonymous>)
    at fetch (/usr/local/lib/node_modules/twist-dl/node_modules/node-fetch/lib/index.js:1407:9)
    at Promise (/usr/local/lib/node_modules/twist-dl/index.js:132:9)

This is true for any episode from that season of the anime.

Thanks in advance!

**Comment by vignedev** [comment]
Hey there,

I just pushed a fix for this in 2a9a5e58862fd53a358b000fc5515fc2494370b7. If you can, please try testing the `master` branch, otherwise please wait a bit until I update the `npm`.

**Comment by hennemon** [comment]
That was fast. Thank you for the quick fix. I will test it once the npm is updated.

**Comment by vignedev** [comment]
Hi there,

I just published the fix onto `npm`. Feel free to reopen this issue if needed.
