### ISSUE TITLE
When multiple anime start with the provided `--anime` flag, allow the user to pick the correct anime via command line arguments

### ISSUE THREAD

**Issue by Scripter17** [vignedev/twist-dl#3]
I'm trying to download the entirety JoJo's Bizarre Adventure, but downloading it is frustrating because the name for the first season, `jojo-s-bizarre-adventure`, is also the start for the other 4 seasons.

A potential fix would be to allow a RegEx for the `--anime` flag (`--anime-reg`?), or to at least allow a method of saying "This is the entire title; Do not match anything else". (perhaps `'jojo-s-bizarre-adventure'`. Note the single quotes, because in Windows command prompt there is no easy way to pass a double quote as an argument)

For now, doing `twist-dl -e 1-9` then selecting the correct anime from the drop-down works, but is unweildly. Not to mention that trying to automate downloading all anime in a list would be severely limited by that, as it requires user input.

If there's already a solution for this, then I'd like it to be made more clear in the help message.  
Note: attempting to do `twist-dl twist.moe/a/jojo-s-bizarre-adventure/1` results in downloading DIU (`jojo-s-bizarre-adventure-diamond-is-unbreakable`), and attempting to use the `--episode` flag with a URL simply outputs the help text

**Comment by vignedev** [comment]
Hey there,

I've just updated it so it first looks for complete matches and then for other possible matches. This should fix the issues with `jojo-s-bizarre-adventure` being redirected to `jojo-s-bizarre-adventure-diamond-is-unbreakable`. However I didn't have enough time to test it, so I'll publish it on npm on a later date. Please clone the repository to test this feature.

Regarding the point about downloading all episodes: for now there is no way to download them all without either knowing the episode count beforehand and passing it as an `episode` argument or selecting them from the list (pressing A will select everything on the list). I'll consider adding it later on.

Also sorry, can you clarify what you meant by the double quotes on Windows?

**Comment by Scripter17** [comment]
After a bit of fighting with the path windows-variable-thingie (weird story, not important), I have determined that `jojo-s-bizarre-adventure` no longer maps to `jojo-s-bizarre-adventure-diamond-is-unbreakable`. So hopefully that's over and done with.

The thing about double quotes is moot due to you making it look for full matches first, but basically there's no easy (if any) way to pass a double quote (`"`) into the batch command line as an argument. You can do it in Power Shell, but when's the last time anyone used *that*?

`argtest.js` is just the line `console.log(process.argv);`

![image](https://user-images.githubusercontent.com/25886989/70580978-9a343580-1b83-11ea-8578-c322b7a544f2.png)

Note especially that the argument `"1 "2" 3"` came out not only without the start and end quotes, but without the ones around the 2.  
I'm sure it's theoretically possible, but generally it's best to just use single quotes.

Not sure if you'd consider this issue done, so I'll let you decide if it should be closed.
