### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by giusy** [vignedev/twist-dl#4]
is it only me? 
error:  Failed to download episode
 Server responded with 403 (Forbidden)

**Comment by vignedev** [comment]
Nope, it's not only you.

twist.moe has recently introduced an additional layer of security in form of Sucuri Website Firewall. Currently looking into ways to workaround it, but it's not looking too bright.

**Comment by vignedev** [comment]
Accidentally closed the issue.

I have updated both the repository and npm, can you please test if the issue still persists?

**Comment by giusy** [comment]
thx it's working perfectly 👍
