### ISSUE TITLE
Can not run script on Ubuntu 18.04 Server

### ISSUE THREAD

**Issue by Awooiel** [vignedev/twist-dl#6]
I am running a fresh Ubuntu 18.04 Server install under the root user
I install nodeJS and npm from this repository using curl without any issues or errors
https://deb.nodesource.com/setup_12.x

I checked the NodeJS version and npm version and I get this back
npm -v 6.13.4 | nodejs -v v12.16.1

After that I ran 
npm i twist-dl -g
It downloaded/installed the module without any issues

However when I run the twist-dl script I get this back every time and nothing else.

/usr/bin/env: ‘node\r’: No such file or directory

I have tried a bunch of different ways of installing nodejs, npm; I still have this problem with different version of nodejs as well.
I have tried it on a windows machine and have had no issues. I am only having issues with Ubuntu 18.04 Server

**Comment by vignedev** [comment]
Weird, I'm currently running Clear Linux and Termux and both work fine. I wasn't able to reproduce this issue. I've both checked the git version and npm and neither of them contain the `\r` character.

While I'm not exactly fluent in Linux, I can see this happening for a few reasons.
1. Can you try and see if the `node` command is present in your PATH?
2. Can you try cloning the repository and installing it with `npm i . -g`?
3. Can you try editing the `bin/twist-dl` and removing `\r`? (You can use `dos2unix` if that's available to you)

**Comment by vignedev** [comment]
I have for curiosity sakes installed Ubuntu Server 18.04 in VirtualBox but I still wasn't able to reproduce the issue you have. Does the issue still persist for you?

**Comment by vignedev** [comment]
Closed due to inactivity.

Please feel free to reopen this issue if the problem still persists.
