### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by gauraputu** [vignedev/twist-dl#7]
I keep getting this error

> error:  { Error: EEXIST: file already exists, mkdir '/home/darmini'
>     at Object.fs.mkdirSync (fs.js:885:18)
>     at /usr/local/lib/node_modules/twist-dl/index.js:78:12
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>   errno: -17,
>   code: 'EEXIST',
>   syscall: 'mkdir',
>   path: '/home/darmini' }
>

**Comment by vignedev** [comment]
Can you please state your node version?

```bash
$ node -v
```

**Comment by vignedev** [comment]
I have updated the code to support Node below v10.12.0 (where `fs.mkdir` finally got `recursive` option). The update has also been uploaded to npm.

However to further confirm my suspicions about this issue, please state your Node version.

**Comment by gauraputu** [comment]
it fixed thanks! I checked my node version and it's v8.10.0
