### ISSUE TITLE
Feature request: List URLs without download

### ISSUE THREAD

**Issue by smhmd** [vignedev/twist-dl#9]
A `-l` flag to list URLs without download to potentially pipe those into `mpv --playlist=-`; good ol' unix way.

Thanks

**Comment by vignedev** [comment]
Hey there!

I've already pushed said feature and will publish onto npm after further testing. While the feature *does* work, you have to specify a Referrer HTTP header so the player of your choosing uses it.

mpv example:
```bash
$ twist-dl -a "..." -e 1-12 -l | mpv --playlist=- --referrer=https://twist.moe
```

**Comment by smhmd** [comment]
Yes! got it. Thanks!

**Comment by smhmd** [comment]
It's clear that the feature is not finished yet, and you probably already know this, but for the `-l` flag to make sense in case of outputing to a file,issues and donation dialogs shouldn't be outputed. Using `-a` and `-e` works, but using the interactive selector results in this:
![image](https://user-images.githubusercontent.com/46059092/89932722-9c143400-dbfd-11ea-97b6-6412c9645040.png)

**Comment by vignedev** [comment]
Oops, I overlooked the fact that enquirer defaults the output to stdout. 731d245b6ab36630319ea4e377f190202d13c2fd should fix it allowing interactive mode to be used with `-l` to players.

**Comment by smhmd** [comment]
Works great. Thanks.
